### ISSUE TITLE
Error in read_spectra() import: Error in matrix...

### ISSUE THREAD

**Issue by bethfallon** [annakat/spectrolab#19]
When using the read_spectra() function in RStudio R 3.2.3 on Windows 10 machine, I get the following error:

> dir_path <- system.file("extdata", "Acer_example", package = "spectrolab")
> acer_spectra <- read_spectra(path = dir_path, format = "sig")
Error in matrix(value, n, p) : 
  'data' must be of a vector type, was 'NULL'

Thanks- Beth

**Comment by meireles** [comment]
@bethfallon I have the feeling that the problem is the separator using in the svc parser. I have just updated it in  46a9b1d. Can you try to reinstall `spectrolab` and report back?
Thx!

**Comment by meireles** [comment]
@bethfallon It seemed to be an issue with the metadata constructor (calling matrix() with an expty first argument). This commit def4c0beeaaf572f07591834442b61950e9d0c75 should fix it. Let me know.

**Comment by bethfallon** [comment]
I reinstalled most recent commit, annakat-spectrolab-def4c0b, and I am still getting the same error as I attempt read_spectra() with the acer example data.

**Comment by meireles** [comment]
crap. No idea of what is going on then.

**Comment by meireles** [comment]
@bethfallon OK. The issue was a bug in your version of R. Try installing the latest version (3.3.2) and the problem should be gone.
